# config/packages/framework.yaml
framework:
    secret: "%env(APP_SECRET)%"
    default_locale: "fr"

    # Configuration correcte de la session pour Symfony 7
    session:
        handler_id: null
        cookie_secure: 'auto'
        cookie_samesite: 'lax'
        storage_factory_id: 'session.storage.factory.native'

    trusted_hosts: ['^127\.0\.0\.1$', '^localhost$']

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
