security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Authentification par formulaire
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: home

            logout:
                path: app_logout
                target: landing

    access_control:
        # Routes PUBLIQUES - accessibles sans connexion
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/selection, roles: PUBLIC_ACCESS }        # 🌟 PAGE D'ACCUEIL PUBLIQUE
        - { path: ^/movie/, roles: PUBLIC_ACCESS }           # Détails des films
        - { path: ^/tv/, roles: PUBLIC_ACCESS }              # Détails des séries
        - { path: ^/list/, roles: PUBLIC_ACCESS }            # Listes de films par genre
        - { path: ^/cinema, roles: PUBLIC_ACCESS }           # Films au cinéma
        - { path: ^/search, roles: PUBLIC_ACCESS }           # Recherche
        - { path: ^/api/search, roles: PUBLIC_ACCESS }       # API de recherche

        # Quiz PUBLICS - tout le monde peut jouer
        - { path: ^/quiz$, roles: PUBLIC_ACCESS }
        - { path: ^/quiz/\d+$, roles: PUBLIC_ACCESS }        # Détails d'un quiz
        - { path: ^/quiz/\d+/play, roles: PUBLIC_ACCESS }    # Jouer à un quiz

        # Administration des quiz - ADMIN uniquement
        - { path: ^/admin/quiz, roles: ROLE_ADMIN }

        # Fonctionnalités UTILISATEURS CONNECTÉS uniquement
        - { path: ^/quiz/\d+/submit, roles: ROLE_USER }      # Soumettre réponses = connexion requise
        - { path: ^/quiz/mes-resultats, roles: ROLE_USER }   # Voir ses résultats
        - { path: ^/liste, roles: ROLE_USER }                # Gérer ses listes
        - { path: ^/mes-listes, roles: ROLE_USER }           # Voir ses listes

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
