# =============================================================================
# CONFIGURATION DES SERVICES - CINEQUEST / WHATTOWATCHV8
# =============================================================================

services:
    # Configuration par défaut pour les services auto-wirés
    _defaults:
        autowire: true
        autoconfigure: true

    # Enregistre automatiquement tous les services dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # =============================================================================
    # SERVICE DE GÉOLOCALISATION DES SÉANCES (MovieGlu)
    # =============================================================================
    App\Service\ShowtimesProvider:
        arguments:
            $client: '@http_client'
            $cache: '@cache.app'
            $logger: '@logger'
            # Ces valeurs viennent du .env.local
            $apiUrl: '%env(MOVIEGLU_API_URL)%'
            $clientId: '%env(MOVIEGLU_CLIENT)%'
            $apiKey: '%env(MOVIEGLU_API_KEY)%'
            $territory: '%env(MOVIEGLU_TERRITORY)%'
            $auth: '%env(MOVIEGLU_AUTH)%'

    # =============================================================================
    # AUTRES SERVICES
    # =============================================================================
    App\Service\MovieBadgeService: ~

    # Controllers
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

# =============================================================================
# NOTE IMPORTANTE :
# Les alias cache.app et http_client sont automatiquement fournis par Symfony
# Ne PAS les redéfinir ici car cela crée des références circulaires !
# =============================================================================
